"""
ZeroInject — Document Analyzer Module
Visual integrity checks + text authenticity analysis
"""

import io
import re
import hashlib
from collections import Counter
from typing import Optional


def extract_text(file_bytes: bytes, filename: str) -> str:
    """Extract text from PDF or image files."""
    ext = filename.lower().rsplit(".", 1)[-1] if "." in filename else ""

    if ext == "pdf":
        return _extract_pdf_text(file_bytes)
    elif ext in ("png", "jpg", "jpeg", "tiff", "bmp", "gif", "webp"):
        return _extract_image_text(file_bytes)
    else:
        # Try PDF first, then image
        text = _extract_pdf_text(file_bytes)
        if text.strip():
            return text
        return _extract_image_text(file_bytes)


def _extract_pdf_text(file_bytes: bytes) -> str:
    """Extract text from PDF using PyPDF2."""
    try:
        from PyPDF2 import PdfReader
        reader = PdfReader(io.BytesIO(file_bytes))
        text_parts = []
        for page in reader.pages:
            page_text = page.extract_text()
            if page_text:
                text_parts.append(page_text)
        return "\n".join(text_parts) if text_parts else "[No extractable text found in PDF]"
    except Exception as e:
        return f"[PDF extraction error: {str(e)}]"


def _extract_image_text(file_bytes: bytes) -> str:
    """Extract text from image using pytesseract OCR."""
    try:
        from PIL import Image
        import pytesseract
        image = Image.open(io.BytesIO(file_bytes))
        text = pytesseract.image_to_string(image)
        return text if text.strip() else "[No text detected in image]"
    except ImportError:
        return "[OCR unavailable — pytesseract not installed]"
    except Exception as e:
        return f"[Image OCR error: {str(e)}]"


def check_visual_integrity(file_bytes: bytes, filename: str) -> dict:
    """
    Perform visual integrity checks on the document.
    Returns score 0-100 (0=clean, 100=suspicious), flags, and status.
    """
    flags = []
    score = 0
    ext = filename.lower().rsplit(".", 1)[-1] if "." in filename else ""

    # --- Check 1: File size anomalies ---
    size_kb = len(file_bytes) / 1024
    if size_kb < 1:
        flags.append("Suspiciously small file size (<1KB)")
        score += 25
    elif size_kb < 5:
        flags.append("Very small file size (<5KB) — may lack real content")
        score += 15
    elif size_kb > 50000:
        flags.append("Unusually large file (>50MB)")
        score += 10

    # --- Check 2: PDF-specific checks ---
    if ext == "pdf":
        try:
            from PyPDF2 import PdfReader
            reader = PdfReader(io.BytesIO(file_bytes))

            # Check for embedded JavaScript
            for page in reader.pages:
                if "/JS" in str(page) or "/JavaScript" in str(page):
                    flags.append("Embedded JavaScript detected in PDF — HIGH RISK")
                    score += 35

            # Check page count vs file size ratio
            num_pages = len(reader.pages)
            if num_pages > 0:
                kb_per_page = size_kb / num_pages
                if kb_per_page < 0.5:
                    flags.append("Abnormally low content density per page")
                    score += 15

            # Check metadata
            meta = reader.metadata
            if meta:
                producer = str(meta.get("/Producer", ""))
                creator = str(meta.get("/Creator", ""))
                if any(tool in producer.lower() for tool in ["wkhtmltopdf", "phantom", "headless"]):
                    flags.append(f"Generated by automation tool: {producer}")
                    score += 20
                if any(tool in creator.lower() for tool in ["canva", "photoshop", "gimp"]):
                    flags.append(f"Created with image editor: {creator}")
                    score += 10
            else:
                flags.append("Missing PDF metadata — potential stripped document")
                score += 10

            # Check for multiple content streams (potential hidden layers)
            for page in reader.pages:
                contents = page.get("/Contents")
                if contents and isinstance(contents, list) and len(contents) > 3:
                    flags.append("Multiple content streams detected — possible hidden layers")
                    score += 15
                    break

        except Exception as e:
            flags.append(f"PDF analysis error: {str(e)}")
            score += 5

    # --- Check 3: Image-specific checks ---
    elif ext in ("png", "jpg", "jpeg", "tiff", "bmp", "gif", "webp"):
        try:
            from PIL import Image
            from PIL.ExifTags import TAGS
            img = Image.open(io.BytesIO(file_bytes))

            # Check EXIF for AI generation markers
            exif_data = img.getexif()
            if exif_data:
                for tag_id, value in exif_data.items():
                    tag_name = TAGS.get(tag_id, str(tag_id))
                    val_str = str(value).lower()
                    if any(ai in val_str for ai in ["dall-e", "midjourney", "stable diffusion",
                                                      "ai generated", "artificial"]):
                        flags.append(f"AI generation marker in EXIF: {tag_name}={value}")
                        score += 30
                    if any(editor in val_str for editor in ["photoshop", "gimp", "paint.net"]):
                        flags.append(f"Image editing software detected: {tag_name}={value}")
                        score += 10
            else:
                # No EXIF might mean stripped metadata
                if ext in ("jpg", "jpeg"):
                    flags.append("No EXIF data in JPEG — metadata may have been stripped")
                    score += 8

            # Check image dimensions for anomalies
            w, h = img.size
            if w < 100 or h < 100:
                flags.append(f"Very small image dimensions ({w}x{h})")
                score += 15

        except Exception as e:
            flags.append(f"Image analysis error: {str(e)}")
            score += 5

    # Cap score at 100
    score = min(score, 100)

    # Determine status
    if score <= 30:
        status = "PASS"
    elif score <= 60:
        status = "WARN"
    else:
        status = "FAIL"

    if not flags:
        flags.append("No visual integrity issues detected")

    return {
        "score": score,
        "flags": flags,
        "status": status,
        "file_size_kb": round(size_kb, 2),
        "file_type": ext or "unknown"
    }


def check_text_authenticity(text: str) -> dict:
    """
    Analyze extracted text for signs of synthetic or fraudulent content.
    Returns score 0-100 (0=clean, 100=suspicious), flags, and status.
    """
    flags = []
    score = 0

    if not text or text.startswith("["):
        # No real text to analyze
        return {
            "score": 0,
            "flags": ["No text content available for analysis"],
            "status": "PASS"
        }

    # --- Check 1: Inconsistent date formats ---
    date_patterns = {
        "MM/DD/YYYY": r'\b\d{1,2}/\d{1,2}/\d{4}\b',
        "DD-MM-YYYY": r'\b\d{1,2}-\d{1,2}-\d{4}\b',
        "YYYY-MM-DD": r'\b\d{4}-\d{1,2}-\d{1,2}\b',
        "DD.MM.YYYY": r'\b\d{1,2}\.\d{1,2}\.\d{4}\b',
        "Month DD, YYYY": r'\b(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s+\d{1,2},?\s+\d{4}\b',
    }
    formats_found = []
    for fmt_name, pattern in date_patterns.items():
        if re.search(pattern, text):
            formats_found.append(fmt_name)
    if len(formats_found) > 1:
        flags.append(f"Inconsistent date formats detected: {', '.join(formats_found)}")
        score += 20

    # --- Check 2: Copy-pasted boilerplate (repeated 5+ word phrases) ---
    words = text.split()
    if len(words) > 20:
        five_grams = [" ".join(words[i:i+5]) for i in range(len(words) - 4)]
        phrase_counts = Counter(five_grams)
        repeated = {phrase: count for phrase, count in phrase_counts.items() if count >= 2}
        if len(repeated) > 3:
            flags.append(f"Repeated phrase patterns found ({len(repeated)} duplicated 5-word sequences)")
            score += 20
        elif repeated:
            flags.append(f"Minor text repetition detected ({len(repeated)} repeated phrases)")
            score += 8

    # --- Check 3: Suspicious Unicode characters ---
    unicode_checks = [
        ("\u200b", "Zero-width space"),
        ("\u200c", "Zero-width non-joiner"),
        ("\u200d", "Zero-width joiner"),
        ("\u2060", "Word joiner"),
        ("\ufeff", "Zero-width no-break space"),
        ("\u200e", "Left-to-right mark"),
        ("\u200f", "Right-to-left mark"),
        ("\u202a", "Left-to-right embedding"),
        ("\u202b", "Right-to-left embedding"),
    ]
    found_unicode = []
    for char, name in unicode_checks:
        count = text.count(char)
        if count > 0:
            found_unicode.append(f"{name} (×{count})")
    if found_unicode:
        flags.append(f"Suspicious Unicode characters: {', '.join(found_unicode)}")
        score += 25

    # Check for homoglyphs (Cyrillic letters that look like Latin)
    homoglyphs = {
        'а': 'a', 'е': 'e', 'о': 'o', 'р': 'p', 'с': 'c',
        'у': 'y', 'х': 'x', 'А': 'A', 'В': 'B', 'Е': 'E',
        'К': 'K', 'М': 'M', 'Н': 'H', 'О': 'O', 'Р': 'P',
        'С': 'C', 'Т': 'T', 'Х': 'X',
    }
    homoglyph_found = False
    for cyrillic, latin in homoglyphs.items():
        if cyrillic in text:
            homoglyph_found = True
            break
    if homoglyph_found:
        flags.append("Homoglyph characters detected (Cyrillic letters disguised as Latin)")
        score += 25

    # --- Check 4: Unrealistic statistics ---
    unrealistic_patterns = [
        (r'\b100\s*%\s*(?:success|accuracy|satisfaction|compliance|approval)\s*rate\b', "100% success/accuracy rate"),
        (r'\b0\s*%?\s*(?:error|failure|rejection|complaint)\s*rate\b', "0% error/failure rate"),
        (r'\b(?:guaranteed|100%\s*guaranteed)\b', "Guaranteed outcome claim"),
        (r'\bno\s+(?:risk|downside|disadvantage)\b', "No risk claim"),
    ]
    for pattern, description in unrealistic_patterns:
        if re.search(pattern, text, re.IGNORECASE):
            flags.append(f"Unrealistic claim: {description}")
            score += 10

    # --- Check 5: Missing expected fields ---
    # Check if document mentions "invoice" but lacks key invoice fields
    text_lower = text.lower()
    if "invoice" in text_lower:
        missing_fields = []
        for field in ["total", "amount", "date", "invoice number", "bill to"]:
            if field not in text_lower:
                missing_fields.append(field)
        if len(missing_fields) >= 3:
            flags.append(f"Invoice document missing expected fields: {', '.join(missing_fields)}")
            score += 15

    # Cap score at 100
    score = min(score, 100)

    if score <= 30:
        status = "PASS"
    elif score <= 60:
        status = "WARN"
    else:
        status = "FAIL"

    if not flags:
        flags.append("No text authenticity issues detected")

    return {
        "score": score,
        "flags": flags,
        "status": status
    }
